@startuml

actor "__client__:__user__" as client
boundary UI
control "__settingsCont__: settings_controller" as SC
control "__brandCont__: __brand_controller__" as BC

control "__accsCont__:__account_controller__" as AC
entity Brand
database database

activate client 
activate UI
client -> UI: add another name to track
activate AC
UI -> AC: getUserBrands(client)
activate database
AC -> database: fetch all user brands
AC --> UI:
deactivate AC
UI --> client: Show all User's Brands
UI <- client: select brand
activate BC
UI -> BC : getBrandAltNames(userSelectedBrand)
activate Brand
BC -> Brand: getAltNames()
Brand -> database : query for all brand alt names
BC --> UI: list of names
deactivate BC
UI --> client : display all existing brand names
UI <-- client: enter new name with language
activate SC
UI -> SC: addAltName(UserSelectedBrand,name)
SC -> Brand: addAltName(name)
Brand -> database : query to add names
deactivate database
deactivate Brand
SC -> UI : added names
deactivate SC
UI -> client: added names
deactivate client 
deactivate UI


@enduml